
package webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-03T17:38:55.659+02:00
 * Generated source version: 3.1.0
 * 
 */
public final class UtilFechaSoap_UtilFechaSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice/", "UtilFechaSoapService");

    private UtilFechaSoap_UtilFechaSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UtilFechaSoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UtilFechaSoapService ss = new UtilFechaSoapService(wsdlURL, SERVICE_NAME);
        UtilFechaSoap port = ss.getUtilFechaSoapPort();  
        
        {
        System.out.println("Invoking esBisiesto...");
        javax.xml.datatype.XMLGregorianCalendar _esBisiesto_arg0 = null;
        java.lang.Boolean _esBisiesto__return = port.esBisiesto(_esBisiesto_arg0);
        System.out.println("esBisiesto.result=" + _esBisiesto__return);


        }
        {
        System.out.println("Invoking getDia...");
        javax.xml.datatype.XMLGregorianCalendar _getDia_arg0 = null;
        java.lang.String _getDia__return = port.getDia(_getDia_arg0);
        System.out.println("getDia.result=" + _getDia__return);


        }

        System.exit(0);
    }

}
