package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-03T17:38:55.725+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://webservice/", name = "UtilFechaSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface UtilFechaSoap {

    @WebMethod
    @RequestWrapper(localName = "esBisiesto", targetNamespace = "http://webservice/", className = "webservice.EsBisiesto")
    @ResponseWrapper(localName = "esBisiestoResponse", targetNamespace = "http://webservice/", className = "webservice.EsBisiestoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean esBisiesto(
        @WebParam(name = "arg0", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getDia", targetNamespace = "http://webservice/", className = "webservice.GetDia")
    @ResponseWrapper(localName = "getDiaResponse", targetNamespace = "http://webservice/", className = "webservice.GetDiaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getDia(
        @WebParam(name = "arg0", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg0
    );
}
