package calculator.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-02T18:19:43.025+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "CalculadoraSoap", 
                  wsdlLocation = "http://localhost:8080/ejercicio1/service/CalculadoraSoap?wsdl",
                  targetNamespace = "webservice.calculator") 
public class CalculadoraSoap_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("webservice.calculator", "CalculadoraSoap");
    public final static QName CalculadoraSoapPort = new QName("webservice.calculator", "CalculadoraSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ejercicio1/service/CalculadoraSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculadoraSoap_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ejercicio1/service/CalculadoraSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculadoraSoap_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculadoraSoap_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraSoap_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CalculadoraSoap_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculadoraSoap_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculadoraSoap_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CalculadoraSoap
     */
    @WebEndpoint(name = "CalculadoraSoapPort")
    public CalculadoraSoap getCalculadoraSoapPort() {
        return super.getPort(CalculadoraSoapPort, CalculadoraSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraSoap
     */
    @WebEndpoint(name = "CalculadoraSoapPort")
    public CalculadoraSoap getCalculadoraSoapPort(WebServiceFeature... features) {
        return super.getPort(CalculadoraSoapPort, CalculadoraSoap.class, features);
    }

}
