package calculator.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-02T18:19:43.016+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "webservice.calculator", name = "CalculadoraSoap")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CalculadoraSoap {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "webservice.calculator", partName = "return")
    public float divide(
        @WebParam(partName = "op1", name = "op1")
        float op1,
        @WebParam(partName = "op2", name = "op2")
        float op2
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "webservice.calculator", partName = "return")
    public float sum(
        @WebParam(partName = "op1", name = "op1")
        float op1,
        @WebParam(partName = "op2", name = "op2")
        float op2
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "webservice.calculator", partName = "return")
    public float multiply(
        @WebParam(partName = "op1", name = "op1")
        float op1,
        @WebParam(partName = "op2", name = "op2")
        float op2
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "webservice.calculator", partName = "return")
    public float substract(
        @WebParam(partName = "op1", name = "op1")
        float op1,
        @WebParam(partName = "op2", name = "op2")
        float op2
    );
}
